Expenses/Controllers/ApiController.cs
using Expenses.Model;
using Expenses.Models;
using Expenses.Models.Data;
using Expenses.Models.ImportExports;
using Expenses.Models.ViewModel;
using Expenses.MySQLRepository;
using Expenses.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Expenses.Controllers
{
    //[Route("api/[controller]")]
    [Authorize]
    public class ApiController : Controller
    {

        private ILogger<HomeController> _logger;
        private UserManager<AppUser> userMgr;
        private SignInManager<AppUser> signMgr;
        private IUserRepository userRepository;
        private IGroupRepository groupRepository;
        private IPaymentRepository paymentRepository;

        public ApiController(ILogger<HomeController> logger, UserManager<AppUser> userMgr,
            SignInManager<AppUser> signMgr, IUserRepository userRepository,
            IGroupRepository groupRepository, IPaymentRepository paymentRepository)
        {
            _logger = logger;
            this.userMgr = userMgr;
            this.signMgr = signMgr;
            this.userRepository = userRepository;
            this.groupRepository = groupRepository;
            this.paymentRepository = paymentRepository;
        }
        [HttpGet]
        public IActionResult prvi()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetMonthLimits([FromBody] MonthRangeModel range)
        {
            // Get from date
            // Get to date
            AppUser appUser = await userMgr.GetUserAsync(this.HttpContext.User);
            if (appUser == null)
                return NotFound(new { Error = "User not logged in!" });
            User user = userRepository.GetUser(appUser.Email);
            if (user == null)
                return NotFound(new { Error = "User not found!" });

            var groups = groupRepository.GetGroups(user.Id);

            if (ModelState.IsValid)
            {
                int startDay = user.FirstDayInMonth;
                if (startDay == 0)
                    startDay = 1;
                // Set start and end date so it first FirstDayInMonth.
                //var d = range.StartDate;
                int startYear = MonthCalculator.GetYear(startDay, range.StartDate);
                int startMonth = MonthCalculator.GetMonth(startDay, range.StartDate);
                int endYear = MonthCalculator.GetYear(startDay, range.EndDate);
                int entMonth = MonthCalculator.GetMonth(startDay, range.EndDate);
                DateTime startD = MonthCalculator.GetStartPeriod(startDay, startYear, startMonth);// new DateTime(d.Year, d.Month, 1, 0, 0, 0);
                //d = range.EndDate;
                DateTime endD = MonthCalculator.GetEndPeriod(startDay, endYear, entMonth);
                //if (startDay > 15)
                //    startD = startD.AddMonths(-1);
                //else
                //    endD = endD.AddMonths(1);
                //startD = startD.AddDays(startDay - 1);
                //endD = endD.AddDays(startDay - 1);

                var payments = paymentRepository.GetAllForUser(user.Id, startD, endD)
                    //.GetAll((p) => startD <= p.PurchaseDate && p.PurchaseDate <= endD)
                    .OrderBy(x => x.PurchaseDate)
                    .ToList();

                // Prepare date ranges.
                var paymentsDic = new[] { new { Date = DateTime.Now, Limit = new List<Limit>(), Payments = new List<Payment>() } }.ToList();
                paymentsDic.Clear();
                DateTime tempDate = startD;
                while (tempDate < endD)
                {
                    paymentsDic.Add(new { Date = tempDate, Limit = new List<Limit>(), Payments = new List<Payment>() });
                    tempDate = tempDate.AddMonths(1);
                }
                // Assign existing limits. 
                if (user.Limit != null)
                    for (int i = 0; i < user.Limit.Count; i++)
                    {
                        Limit lm = user.Limit.ElementAt(i);
                        DateTime lmStart = MonthCalculator.GetStartPeriod(startDay, lm.StartDate);
                        if (lmStart < startD || endD < lmStart)
                            continue;
                        for (int j = 0; j < paymentsDic.Count; j++)
                        {
                            DateTime dt = paymentsDic[j].Date;
                            if (lmStart <= dt && dt <= lmStart.AddMonths(1))
                            {
                                paymentsDic[j].Limit.Add(lm);
                                break;
                            }
                        }
                    }
                // Initial limit is not in date range. Try to find previous one.
                if (!paymentsDic[0].Limit.Any())
                {
                    var pl = user.GetPreviousLimit(startD);
                    Limit l = new Limit() { TopAmount = 0, BottomAmount = 0, StartDate = startD };
                    if (pl != null)
                    {
                        l.TopAmount = pl.TopAmount;
                        l.BottomAmount = pl.BottomAmount;
                    }
                    paymentsDic[0].Limit.Add(l);
                }

                // Where limits are not set, use previous one.
                for (int i = 0; i < paymentsDic.Count; i++)
                {
                    var v = paymentsDic[i];
                    if (!v.Limit.Any())
                    {
                        if (i == 0)
                        {
                            // This should have been handled before.
                            //Limit l = new Limit() { TopAmount = 0, BottomAmount = 0, StartDate = v.Date };
                            //v.Limit.Add(l);
                        }
                        else
                        {
                            var previous = paymentsDic[i - 1].Limit.First();
                            v.Limit.Add(new Limit()
                            {
                                StartDate = previous.StartDate.AddMonths(1),
                                TopAmount = previous.TopAmount,
                                BottomAmount = previous.BottomAmount
                            });
                        }
                    }
                }

                // Assign payments and limits to date ranges.
                for (int i = 0; i < payments.Count; i++)
                {
                    var p = payments[i];
                    int j = 0;
                    while (paymentsDic[j].Date.AddMonths(1) < p.PurchaseDate)
                        j++;
                    if (j > paymentsDic.Count)
                        throw new InvalidOperationException("Payment is out of date range!");
                    paymentsDic[j].Payments.Add(p);
                }
                List<MonthLimitsModel> months = new List<MonthLimitsModel>();
                // Calculate payments in each month.
                for (int i = 0; i < paymentsDic.Count; i++)
                {
                    var p = paymentsDic[i];
                    var m = new MonthLimitsModel();
                    m.TopLimit = p.Limit.First().TopAmount;
                    m.BottomLimit = p.Limit.First().BottomAmount;
                    m.Spent = p.Payments.Sum(x => x.TotalAmount);
                    m.StartDate = p.Date;
                    m.Month = MonthCalculator.GetMonth(startDay, p.Date);
                    m.Year = MonthCalculator.GetYear(startDay, p.Date);
                    m.EndDate = p.Date.AddMonths(1);
                    months.Add(m);
                }
                MonthsModel model = new MonthsModel();
                model.StartDate = startD;
                model.EndDate = endD;
                model.Months = months;

                // create collection
                return new JsonResult(model);
            }
            return BadRequest("Invalid data is sent");
        }

        [HttpPost]
        public IActionResult ChangeGroup([FromBody] GroupUpdateModel data)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Data is invalid!");
            }
            AppUser appUser = userMgr.GetUserAsync(this.HttpContext.User).Result;
            if (appUser == null)
                return NotFound(new { Error = "User not logged in!" });
            User user = userRepository.GetUser(appUser.Email);
            if (user == null)
                return NotFound(new { Error = "User not found!" });

            var groups = groupRepository.GetGroups(user.Id);

            var gr = groups.FirstOrDefault(x => x.Id == data.Id);
            if (gr == null)
                return BadRequest("Group not found.");

            gr.Name = data.Name;
            gr.Color = data.Color;

            groupRepository.Save(gr);

            return Ok();
        }
        [HttpPost]
        public IActionResult ChangeStartDay([FromBody]int day)
        {
            AppUser appUser = userMgr.GetUserAsync(this.HttpContext.User).Result;
            if (appUser == null)
                return NotFound(new { Error = "User not logged in!" });
            User user = userRepository.GetUser(appUser.Email);
            if (user == null)
                return NotFound(new { Error = "User not found!" });

            user.FirstDayInMonth = day;
            userRepository.Save(user);

            return Ok();
        }
        [HttpPost()]
        public IActionResult ChangeShopName([FromBody] ShopUpdateModel data)
        {

Expenses/Views/Shared/Components/Sidebar/Default.cshtml
@{
	string add = "1";
	string dash = "2";
	string monthly = "33";
	string payments = "3";
	string settings = "4";
	string prefs = "5";
	string account = "6";
	string admin_sett = "7";
	string action = ViewBag.Action;
	Func<string, string> getClass = (a) => action == a ? " active" : "";
	Dictionary<string, string> actions = new Dictionary<string, string>()
	{
		[add] = nameof(AccountController.AddPayment),
		[dash] = nameof(AccountController.Index),
		[monthly] = nameof(AccountController.Monthly),
		[payments] = nameof(AccountController.Payments),
		[settings] = nameof(AccountController.Settings),
		[prefs] = nameof(AccountController.Preferences),
		[account] = nameof(AccountController.Account),
		[admin_sett] = nameof(AccountController.AdminSettings),
	};
	Dictionary<string, string> classes = new Dictionary<string, string>()
	{
		[add] = getClass(actions[add]),
		[dash] = getClass(actions[dash]),
		[monthly] = getClass(actions[monthly]),
		[payments] = getClass(actions[payments]),
		[settings] = getClass(actions[settings]),
		[prefs] = getClass(actions[prefs]),
		[account] = getClass(actions[account]),
		[admin_sett] = getClass(actions[admin_sett]),
	};
	bool isAdmin = ViewBag.IsAdmin ?? false;

}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
	<!-- Brand Logo -->
	<a href="index3.html" class="brand-link">
		<img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
			 style="opacity: .8">
		<span class="brand-text font-weight-light">Expenses manager</span>
	</a>

	<!-- Sidebar -->
	<div class="sidebar">
		<!-- Sidebar user panel (optional) -->
		<div class="user-panel mt-3 pb-3 mb-3 d-flex">
			<div class="image">
				<i class="nav-icon fas fa-user" style="color:white; vertical-align:middle;"></i>
			</div>
			<div class="info">
				<a as href="#" class="d-block">@ViewBag.FullName </a>
			</div>
		</div>


		<!-- Sidebar Menu -->

		<nav class="mt-2">
			<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
				<li class="nav-item">
					<a asp-action="@actions[add]" class="nav-link @classes[add]">
						<i class="nav-icon fas fa-plus-square"></i>
						<p>
							Add Payment<span class="right badge badge-danger">New</span>
						</p>
					</a>
				</li>
				<li class="nav-item">
					<a asp-action="@actions[dash]" class="nav-link @classes[dash]">
						<i class="nav-icon fas fa-home"></i>
						<p>
							Dashboard
						</p>
					</a>
				</li>
				<li class="nav-item">
					<a asp-action="@actions[monthly]" class="nav-link @classes[monthly]">
						<i class="nav-icon fas fa-calendar"></i>
						<p>
							Monthly
						</p>
					</a>
				</li>
				<li class="nav-item">
					<a asp-action="@actions[payments]" class="nav-link @classes[payments]">
						<i class="nav-icon fas fa-list"></i>
						<p>
							Payments
						</p>
					</a>
				</li>
				<li class="nav-item">
					<a asp-action="@actions[settings]" class="nav-link @classes[settings]">
						<i class="nav-icon fas fa-users-cog"></i>
						<p>
							Settings
						</p>
					</a>
				</li>
				@if (false)
				{
					<li class="nav-item">
						<a asp-action="@actions[prefs]" class="nav-link @classes[prefs]">
							<i class="nav-icon fas fa-credit-card"></i>
							<p>
								Payment preferences
							</p>
						</a>
					</li>
					<li class="nav-item">
						<a asp-action="@actions[account]" class="nav-link @classes[account]">
							<i class="nav-icon fas fa-address-card"></i>
							<p>
								Account
							</p>
						</a>
					</li>
				}
				@if (isAdmin)
				{
					<li class="nav-header">Admin</li>

					<li class="nav-item">
						<a asp-action="@actions[admin_sett]" class="nav-link @classes[admin_sett]">
							<i class="nav-icon fas fa-users-cog"></i>
							<p>
								Settings
							</p>
						</a>
					</li>
				}
				<li class="nav-header">Backup</li>

				<li class="nav-item">
					<a asp-action="ExportAll" asp-controller="Api" class="nav-link">
						<i class="nav-icon fas fa-users-cog"></i>
						<p>
							Export
						</p>
					</a>
				</li>
			</ul>
		</nav>

		<!-- /.sidebar-menu -->
	</div>
	<!-- /.sidebar -->
</aside>